### ISSUE TITLE
Easier setup for plugins

### ISSUE THREAD

**Issue by khuongduybui** [svipas/vscode-prettier-plus#10]
Ideally we should be able to use plugin provided in different places, in this order:

1. An explicit path config in VSCode setting
2. In open workspaces local node_modules
3. In environment variable $PATH
4. Globally installed with npm, yarn, or pnpm

**Comment by khuongduybui** [comment]
I think 3 and 4 can be done together.

If you run `npx --no-install <foo>`, it will look for `foo` in both npm global location and also in `$PATH`.
If you run `pnpx --no-install <foo>`, it will look for `foo` in both pnpm global location and also in `$PATH`.
If you run `yarn exec <foo>`, it will look for `foo` in both yarn global location and also in `$PATH`.

**Comment by svipas** [comment]
Fixed in `3.5.0` version.
