### ISSUE TITLE
Cannot use in WSL (remote) after 3.5 update

### ISSUE THREAD

**Issue by khuongduybui** [svipas/vscode-prettier-plus#12]
Since you set the extensionKind to `ui`, it's now installed on VSCode host in Windows and not my `vscode-server` agent inside WSL. I cannot no longer format files in WSL remote workspaces.
There is nothing in the output section of the extension, VSCode just tells me "Extension cannot format file".

**Comment by khuongduybui** [comment]
Note: I installed node, npm, yarn on Windows host and install prettier, eslint, stylint, tslint, @prettier/plugin-ruby with yarn global add too

**Comment by svipas** [comment]
I tried to set to workspace and format Ruby and it was working only then it was set as an ui. Let me try to check it tomorrow and I will try to test it one more time.

**Comment by svipas** [comment]
Fixed in `3.5.2` release.
