### ISSUE TITLE
Can't found the plugin in `Format Document With...` 

### ISSUE THREAD

**Issue by Flcwl** [svipas/vscode-prettier-plus#15]
prettier: 3.6.6

vscode:
```
version: 1.43.1
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by svipas** [comment]
Hi, could you please give more context? What plugin you're using, what file you're trying to format? You can access output of Prettier+ and copy-paste that here. The supported plugins and how to use them are described in README.

**Comment by svipas** [comment]
I got no response to this issue. I'm closing it. If you think this problem still exists, please re-open it and explain me how to reproduce it.
