### ISSUE TITLE
Ruby plugin not working in Docker

### ISSUE THREAD

**Issue by khuongduybui** [svipas/vscode-prettier-plus#18]
I'm using Remote Development on Containers

Inside my docker everything runs as root including VSCode server.

When I try to format a .rb file I got this error in Prettier+ output

```
/usr/local/share/.config/yarn/global does not exist or is not a directory
```

However when I open VSCode terminal and `ls -la /usr/local/share/.config/yarn/global`, it does exists and contains `node_modules/@prettier/plugin-ruby`

**Comment by svipas** [comment]
Seems like Prettier problem. Let us try to upgrade Prettier to v2 and see if the same error happens.

**Comment by svipas** [comment]
Please try to reproduce the same problem with `4.0.0` version of extension which contains Prettier `2.0.5` and let me know. If issue still exists, give me info how to correctly reproduce it.

**Comment by khuongduybui** [comment]
Unfortunately I stopped working on the ruby project. You may close this.
