### ISSUE TITLE
GraphQL Schema not getting formatted.

### ISSUE THREAD

**Issue by sannamalai176** [svipas/vscode-prettier-plus#21]
is there any special setting to format the graphql schemas

**Comment by svipas** [comment]
@sannamalai176 It works for me, no additional setting is required. Use latest version of this extension, set file mode to `graphql` and it should work.

I tried to format these files below and it worked.

```graphql
type Query {
	quoteOfTheDay: String
	random: Float!
	rollThreeDice: [Int]
}
```

```graphql
{
	hero {
		name
		appearsIn
	}
}
```

You could also check output by Prettier+ and see if it returns something like this: `Using prettier@2.0.5 to format code with graphql parser for graphql language.`

**Comment by svipas** [comment]
I'm not getting any info about this issue, I'm closing it. If needed you can re-open it or create a new one.
