### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.iterator'

### ISSUE THREAD

**Issue by domialex** [svipas/vscode-prettier-plus#22]
When trying to format react files I get the following error :
`Cannot find module 'core-js/modules/es.array.iterator'`

Running latest version of Prettier+ 4.1.1 and VSCode.

Oh, I just noticed that it only does that when using the ESlint integration
![image](https://user-images.githubusercontent.com/4694217/84070505-3f489300-a99a-11ea-8dd7-17db13dbf2f0.png)

**Comment by svipas** [comment]
Interesting, I fixed this error by installing missing core-js dependency. Could you please try to delete extension and download it again?

**Comment by davidjj76** [comment]
Same here! Trying with several versions...until version 4.0.2 working well, but last two versions don't seem to work.

**Comment by svipas** [comment]
Should be fixed in `4.1.2` version of extension. Thanks for letting me know about the issue. If issue persists, please re-open the issue or create a new one.

**Comment by sawich** [comment]
still have too

**Comment by svipas** [comment]
@domialex @davidjj76 @sawich Thanks for patience. Should be fixed in `4.2.0`.
