### ISSUE TITLE
svelete and razor file support

### ISSUE THREAD

**Issue by sannamalai76** [svipas/vscode-prettier-plus#23]
How can i use this extension to format .svelete  and .razor extension files, it seems like currently it doesnt offer support.

**Comment by svipas** [comment]
Prettier doesn't support `.razor` files. For `.svelte` there is [plugin](https://github.com/sveltejs/prettier-plugin-svelte), but it isn't officially supported by Prettier. So unfortunately you will need try to use Svelte extension for VS Code and see if it formats your Svelte files, for `.razor` files you could register them as a HTML in VS Code so it supports formatting, but I don't know how good it will be.
