### ISSUE TITLE
Can not format code with version 1.1.0

### ISSUE THREAD

**Issue by blueandhack** [svipas/vscode-prettier-plus#5]
Version 1.1.0 can not format code and prettier not show in the bottom bar.
I saw VSCode said "Prettier+ can not format 'XXX/XX/XX.js'"
So, I just downgrade to 1.0.0, everything works fine.

**Comment by svipas** [comment]
Yeah I know this issue, fixing it right now. Tried to use webpack and bundle everything even `node_modules`, but unfortunately it doesn't work. So instead I will use parcel and I will keep `node_modules` but ignore unnecessary files from it as much as possible to keep bundle smaller.

**Comment by svipas** [comment]
Published `1.2.0` version which now formats code. Also, format messages are fixed and shows what is actually used to format the code and which language is formatted.
