### ISSUE TITLE
Stylelint settings in VSCode settings.json ?

### ISSUE THREAD

**Issue by kanlukasz** [svipas/vscode-prettier-plus#6]
Hey,

I would like to ask you about settings for Stylelint.
Can I set the settings globally?

I see that I can use this with `.stylelintrc.json` in the project root, but I need to use it globally, for all files, not just in a specific project.

Is it possible?

**Comment by svipas** [comment]
Yes, it's possible. You can create a root folder, move projects there and add `.stylelintrc.json` to the root folder and install `stylelint` for every project.

<img width="1552" alt="Screen Shot 2019-08-16 at 01 02 02" src="https://user-images.githubusercontent.com/10441177/63129912-80ae2300-bfc1-11e9-881b-a25fc5cadeec.png">

_But my recommendation is to use same config for every project or simply create a npm package with config and share it across all projects._
