### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by istarwyh** [svipas/vscode-prettier-plus#7]
- Issue Type: `Bug`
- Extension Name: `prettier-plus`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by svipas** [comment]
Hi, thank you for bug report, but I don't quite understand what is wrong?

**Comment by istarwyh** [comment]
I’m very sorry to bother you. This because sometimes the extension crashed and a window that poped up asked if I report the bug. Thank you for your reply.

 

发件人: Benas Svipas <notifications@github.com> 
发送时间: 2019年9月10日 17:20
收件人: svipas/vscode-prettier-plus <vscode-prettier-plus@noreply.github.com>
抄送: yihui wang <yihui@mbin.cc>; Author <author@noreply.github.com>
主题: Re: [svipas/vscode-prettier-plus] Extension issue (#7)

 

Hi, thank you for bug report, but I don't quite understand what is wrong?

**Comment by svipas** [comment]
If it crashes again, please open a new issue with more context it will help me to know what issue it is and I would fix it.

**Comment by istarwyh** [comment]
Ok, thank you for noticing me. And I know how to do next time.

 

发件人: Benas Svipas <notifications@github.com> 
发送时间: 2019年9月11日 12:54
收件人: svipas/vscode-prettier-plus <vscode-prettier-plus@noreply.github.com>
抄送: yihui wang <yihui@mbin.cc>; Author <author@noreply.github.com>
主题: Re: [svipas/vscode-prettier-plus] Extension issue (#7)

 

If it crashes again, please open a new issue with more context it will help me to know what issue it is and I would fix it.
