### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hemantham0002** [svipas/vscode-prettier-plus#9]
- Issue Type: `Performance`
- Extension Name: `prettier-plus`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\<user>\svipas.prettier-plus-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by svipas** [comment]
Could you please give more information? Like attaching the profile, etc.?

**Comment by svipas** [comment]
I'm closing this issue, re-open it if issue still occurs and please include more information, like attaching profile, etc.
